name: Build Android & iOS

on: 
  workflow_dispatch:
    inputs:
      base-branch:
        description: 'Base branch for the Android folder'
        required: true
        default: 'main'
      update-text:
        description: 'App Name'
  # push:
  #   branches:
  #     - main

jobs:
  build-android:
    name: Build Android APK & AAB
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          yarn cache clean
          yarn global add react-native-cli
          yarn global add @react-native-community/cli
          npm i -g corepack
          yarn install

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/*.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant permission to Gradlew
        run: chmod +x android/gradlew

      - name: Build APK & AAB
        run: |
          cd android
          ./gradlew assembleRelease
          ./gradlew bundleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.update-text }}.apk
          path: android/app/build/outputs/apk/release/

  # build-ios:
  #   name: Build iOS Archive
  #   runs-on: macos-latest
  #   needs: build-android

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '18'

  #     - name: Install Dependencies
  #       run: |
  #         npm install

  #     - name: Set up Ruby and Bundler
  #       run: |
  #         brew install ruby
  #         gem install bundler
  #         bundle install --gemfile=ios/Gemfile

  #     - name: Install CocoaPods dependencies
  #       run: |
  #         cd ios
  #         pod install --silent

  #     - name: Build iOS Archive
  #       run: |
  #         cd ios
  #         xcodebuild -workspace YourApp.xcworkspace \ 
  #                    -scheme YourApp \ 
  #                    -sdk iphoneos \ 
  #                    -configuration Release \ 
  #                    -archivePath $PWD/build/YourApp.xcarchive \ 
  #                    archive
